### ISSUE TITLE
Problems not collecting default stats

### ISSUE THREAD

**Issue by chkmyid** [taxidriveer/Examiner#1]
I uploaded Examiner's Korean localized dozens of years ago.
Since this addon collects information through the LibGearExam library, I have rewritten the Korean library format to match the WOW Classic format.
In LibGearExam, there is a problem where the stats in the Base and Enchant sections overlap and become data collection (+7 Stamina is shown as +14 Stamina) and there is also a problem where item-specific stats are not collected. And the default stats according to the player level are not applicable.
Base stats of white characters are not collected, only green characters of enchanted items are collected.

Finally, there are times when items and information from the target player that are very close to me are not displayed.

Can you solve this problem?

**Comment by taxidriveer** [comment]
Hi,
I think this is due to the outdated strings in the KR localisation of LibGearExam. I've tried to update it with the help of wowhead in the new version :
**https://github.com/taxidriveer/Examiner/releases/tag/1.05.1**

Let me know if it fix your issues.

**Comment by chkmyid** [comment]
I have updated the rewritten koKR.lua file first. I'll report to you whenever I need to make any further modifications. Thank you for helping me use this add-on. (#2)
