### ISSUE TITLE
To inspect talents via Details

### ISSUE THREAD

**Issue by IanByun** [taxidriveer/Examiner#12]
1. World of Warcraft/_classic_/Interface/AddOns/Examiner/Examiner.lua
edit line number around 178 as follows
```lua
function ex:PLAYER_TARGET_CHANGED(event)  
    if (cfg.autoInspect) and (UnitExists("target")) then  
        self:DoInspect("target");  
        Details:ShowTalentsPanel()
```
2. (same file as 1) World of Warcraft/_classic_/Interface/AddOns/Examiner/Examiner.lua
edit line number around 755 as follows
```lua
if (openFlag ~= false) and (not self:IsShown()) then
    self:Display();
    InspectFrame = Examiner
    Details:ShowTalentsPanel()
end
```
3. (if using ExaminerButton) World of Warcraft/_classic_/Interface/AddOns/ExaminerButton/ExaminerButton.xml
edit line number around 28, 68, 108 as follows
```lua
InspectUnit("target");
InspectFrame = Examiner
Details:ShowTalentsPanel()
```

**Comment by IanByun** [comment]
result:

![image](https://user-images.githubusercontent.com/6938192/94296309-9a2fe580-ff9d-11ea-9270-c0d81bf73e7c.png)

**Comment by vanillalad** [comment]
Thanks, been looking for this.
I've tested it and everything works fine, switching targets etc.

Why not create a pull request with this fix?

**Comment by IanByun** [comment]
@vanillalad hey good thing you found it useful
I use some modified version of Examiner, so I left as a note here rather than PR
